

UUID = "UUID"
DESC = "DESC"
TITLE = "TITLE"
DATA = "DATA"
TAGS = "TAGS"
STORAGEPRIORITY = "STORAGEPRIORITY"
LEASE = "LEASE"
EXPIRES = "EXPIRES"
LASTUPDATED = "LASTUPDATED"
FWD = "FWD"
PATH = "PATH"

CHEAP = "CHEAP"
PLENTIFUL = "PLENTIFUL"
AUTOBACKUP = "AUTOBACKUP"
FAST = "FAST"
NETWORK = "NETWORK"
DEFAULT = "DEFAULT"

LOCKS = "LOCKS"
